version: '3.8'
services:
  frontend:
    build:
      context: ./chatbot-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend/data:/app/data # Persistent data for backend
    environment:
      NODE_ENV: production
      EMAIL_USER: anmol16072002@gmail.com
      EMAIL_PASS: uejsjcylswegllvv
